### ISSUE TITLE
Feature request: Improved navigation through dropdown lists for existing events/years

### ISSUE THREAD

**Issue by motomatters** [fabricepipart/mgp-timings#142]
The system is extremely powerful, but it is a little cumbersome to use. It is extremely useful to have all of the various methods and endpoints exposed. What would make this even more useful is if there was a simple way of finding the session results you are looking for. 

It would be really useful to have a user interface with dropdown lists/select lists which would allow the user to navigate to find the result they want, similar to the way the MotoGP.com website works. 

So, the navigation path would be:

Year -> Event -> category -> session -> result type (detail, csv, speed, etc) 

For me, I would want tests and races all lumped together in the same Event select list. But I can imagine some people might want to only see races, or only see tests. 

Ideally, the process would be done through AJAX or a similar tech, where each choice in the decision tree automatically selects and returns the available options for the next step. The interface should be as simple as possible. 

Hope this is clear. Ask for clarification if not.

**Comment by fabricepipart** [comment]
Hi

I can't agree more. I already had planned to do just that!
You just motivated me to speed up the development.

Though I don't really plan to make a UI (even simplistic). What I wanted to do was to create a new endpoint but for which you can build the URL progressively:

`https://mgp-timings.teknichrono.fr/results` returns the possibles years
`https://mgp-timings.teknichrono.fr/results/2023` returns the possible races (and tests probably)
`https://mgp-timings.teknichrono.fr/results/2023/MY2` returns the possible categories
`https://mgp-timings.teknichrono.fr/results/2023/MY2/motogp` returns the possible sessions
`https://mgp-timings.teknichrono.fr/results/2023/MY2/motogp/fp3` returns the results of that session

Either this or like you said:
`https://mgp-timings.teknichrono.fr/2023` returns the possible races (and tests probably)
and
`https://mgp-timings.teknichrono.fr/2023/MY2/motogp/fp3` returns the available options for that session
`https://mgp-timings.teknichrono.fr/2023/MY2/motogp/fp3/results` returns the results of that session

And similarly you would have:

`https://mgp-timings.teknichrono.fr/speed/2023/MY2/motogp/fp3` returns the results of that session
`https://mgp-timings.teknichrono.fr/analysis/2023/MY2/motogp/fp3` returns the results of that session

etc ...

And the `/csv` suffix would still remain to convert any list returned as a csv instead of json.
What do you think?

**Comment by fabricepipart** [comment]
Regarding the UI aspect. I could be persuaded to have a UI myself.
But I would way prefer that other people use the API and develop their own UI.
For example if one of the best website that has info from a great journo could integrate it freely if they wanted ;-)

**Comment by motomatters** [comment]
> Hi
> 
> I can't agree more. I already had planned to do just that! You just motivated me to speed up the development.
> 
> Though I don't really plan to make a UI (even simplistic). What I wanted to do was to create a new endpoint but for which you can build the URL progressively:
> 
> `https://mgp-timings.teknichrono.fr/results` returns the possibles years `https://mgp-timings.teknichrono.fr/results/2023` returns the possible races (and tests probably) `https://mgp-timings.teknichrono.fr/results/2023/MY2` returns the possible categories `https://mgp-timings.teknichrono.fr/results/2023/MY2/motogp` returns the possible sessions `https://mgp-timings.teknichrono.fr/results/2023/MY2/motogp/fp3` returns the results of that session
> 
> Either this or like you said: `https://mgp-timings.teknichrono.fr/2023` returns the possible races (and tests probably) and `https://mgp-timings.teknichrono.fr/2023/MY2/motogp/fp3` returns the available options for that session `https://mgp-timings.teknichrono.fr/2023/MY2/motogp/fp3/results` returns the results of that session
> 
> And similarly you would have:
> 
> `https://mgp-timings.teknichrono.fr/speed/2023/MY2/motogp/fp3` returns the results of that session `https://mgp-timings.teknichrono.fr/analysis/2023/MY2/motogp/fp3` returns the results of that session
> 
> etc ...
> 
> And the `/csv` suffix would still remain to convert any list returned as a csv instead of json. What do you think?

This sounds exactly like the sort of thing I could use. What I really want is a way of iterating through everything to find the results that I want. So having a list of endpoints I can iterate through  in a simple Perl script to spit out the appropriate results would be absolutely perfect. 

A simple web UI would be great. But a logical way of drilling down to the results you want would be even better.

**Comment by fabricepipart** [comment]
I'll get started ASAP! This week end and next week will be very busy for me. Probably after.

**Comment by fabricepipart** [comment]
I am on it. Of course that's much more work than expected 🤣 
But API should be much better (as requested) ... I hope !

**Comment by fabricepipart** [comment]
#154 is ongoing. Code is acceptable but still lacking some automated tests.

**Comment by fabricepipart** [comment]
I know you have better to do for the moment but..
Here you are. For example the Q2 results : https://mgp-timings.teknichrono.fr/api/2023/SPA/MOTOGP/Q2
Or the analysis of the Sprint race: https://mgp-timings.teknichrono.fr/api/2023/SPA/MOTOGP/SPR/analysis

**Comment by fabricepipart** [comment]
We should be good for now with the latest addition of CSVs with the new API format.
I'll close this issue for now. Feel fre to reopen as many you want for either improvements, bugs or opinions. This is extremely valuable to me. Thanks !
